# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    
    #Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #Check-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      #RUNs a single command for testing
      - name: Run a one-line script
        env:
          API_STUFF: ${{secrets.API_KEY}}
        run: env
